name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1 ]
        laravel: [ 6, 7, 8, 9 ]
        stability: [ prefer-lowest, prefer-stable ]
        exclude:
          - php: 7.2
            laravel: 8
          - php: 7.2
            laravel: 9
          - php: 7.3
            laravel: 9
          - php: 7.4
            laravel: 9
          - php: 8.1
            laravel: 6
          - php: 8.1
            laravel: 7

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} (${{ matrix.stability }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, json, libxml, mbstring, zip
          tools: composer:v2
          coverage: none
      
      - name: Patch testbench version
        if: matrix.php == 8.1 && matrix.laravel == 8
        run: |
          composer require "orchestra/testbench=^6.23" --dev --no-interaction --no-update

      - name: Install dependencies
        run: |
          composer require "illuminate/support=^${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
